# Generated by Django 4.2 on 2023-05-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('n', 'Not Requested For Approval'), ('p', 'Approval Application on Pending'), ('d', 'Approval Request Declined'), ('a', 'Verified')], default='n', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(choices=[('staff', 'Staff'), ('parent', 'Parent'), ('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('super_admin', 'Super_Admin')], default='staff', max_length=50),
        ),
    ]
