# Generated by Django 4.2 on 2023-10-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonnotes', '0003_lessonnote_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonnote',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
