# Generated by Django 4.2 on 2023-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonnotes', '0004_alter_lessonnote_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='lesson_notes'),
        ),
    ]
