services:
  - name: backend
    runtime: python
    healthCheckPath: /healthz
    buildCommand: python -m pip install --upgrade pip; pip install -r requirements.txt
    startCommand: gunicorn config.wsgi
    autoDeploy: true
    rootDir: /backend

databases:
  - name: schoolwave-staging
    user: schoolwave
    databaseName: schoolwave
