services:
  - name: sw-api-staging
    type: web
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi
    autoDeploy: true
    rootDir: ./backend
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.10
      - key: DATABASE_NAME
        fromDatabase:
          name: staging-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: staging-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: staging-db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: staging-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: staging-db
          property: port
databases:
  - name: sw-db-staging
    user: sw_root
    databaseName: schoolwave
    ipAllowList: []
    plan: free
    region: frankfurt