services:
  - name: sw-api-staging
    type: web
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: ./build.sh
    startCommand: . ./.venv/bin/activate && ./manage.py migrate --no-input && gunicorn config.wsgi
    autoDeploy: true
    rootDir: ./backend
    healthCheckPath: /healthz
    envVars:
      - key: DEBUG
        value: True
      - key: FRONTEND_URL
        value: https://schoolwave-staging.vercel.app
      - key: ALLOWED_HOSTS
        value: vercel.app,sw-api-staging-68z1.onrender.com
      - key: PYTHON_VERSION
        value: 3.9.10
      - key: DATABASE_NAME
        fromDatabase:
          name: sw-db-staging
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: sw-db-staging
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: sw-db-staging
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: sw-db-staging
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: sw-db-staging
          property: port
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: sw-db-staging
    user: sw_root
    databaseName: schoolwave
    ipAllowList: []
    plan: free
    region: frankfurt