services:
  - name: backend-staging
    type: web
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi
    autoDeploy: true
    rootDir: ./backend
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.10
