services:
  sw-postgres:
    container_name: sw-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
