services:
  postgres:
    container_name: schoolwave-postgres
    image: postgres
    networks:
      - backend
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
  app:
    container_name: django-app
    build: .
    networks:
      - backend
    depends_on:
     - postgres
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - DATABASE_HOST=postgres
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
networks:
  backend:
    name: backend