# Generated by Django 4.2 on 2023-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='exam.question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
