# Generated by Django 4.2 on 2023-08-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_classmember_school'),
        ('exam', '0002_answer_school_exam_school_question_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='school',
            field=models.ForeignKey(default='3a9b3639-82c2-4d80-bb3a-f571c111fef9', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(default='3a9b3639-82c2-4d80-bb3a-f571c111fef9', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='school',
            field=models.ForeignKey(default='3a9b3639-82c2-4d80-bb3a-f571c111fef9', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='school',
            field=models.ForeignKey(default='3a9b3639-82c2-4d80-bb3a-f571c111fef9', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
    ]
