# Generated by Django 4.2 on 2023-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_due_date_alter_exam_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, to='exam.question'),
        ),
    ]
