# Generated by Django 4.2 on 2023-08-20 22:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_classmember_school'),
        ('school_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('primary_color', models.CharField(default='#FFFFFF', max_length=50)),
                ('secondary_color', models.CharField(default='#000000', max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': '-created_at',
                'abstract': False,
            },
        ),
    ]
