# Generated by Django 4.2 on 2023-08-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0002_schoolbrand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolbrand',
            options={},
        ),
        migrations.AlterModelTable(
            name='schoolbrand',
            table='school_brand',
        ),
    ]
