# Generated by Django 4.2 on 2023-08-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0004_schoolsettings_staff_code_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='student_code_prefix',
            field=models.CharField(default='STUDENT', max_length=10),
        ),
    ]
