# Generated by Django 4.2 on 2023-08-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0004_alter_schoolbrand_primary_color_and_more'),
        ('school_settings', '0004_schoolsettings_staff_code_prefix_and_more'),
    ]

    operations = [
    ]
