# Generated by Django 4.2 on 2023-08-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0005_merge_20230828_1814'),
        ('school_settings', '0006_merge_20230828_0749'),
    ]

    operations = [
    ]
