# Generated by Django 4.2 on 2023-05-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'get_latest_by': '-created_at'},
        ),
        migrations.AlterModelTable(
            name='class',
            table=None,
        ),
    ]
