# Generated by Django 4.2 on 2023-05-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_alter_class_options_alter_class_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['created_at']},
        ),
    ]
