# Generated by Django 4.2 on 2023-05-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_alter_class_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
        migrations.AlterModelTable(
            name='class',
            table='classes',
        ),
    ]
