# Generated by Django 4.2 on 2023-05-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('parent', 'Parent'), ('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('super_admin', 'Super_Admin')], default='student', max_length=50),
        ),
    ]
