# Generated by Django 4.2 on 2023-05-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresetrequest",
            name="active",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status_code",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="passwordresetrequest",
            table="password_reset_requests",
        ),
    ]
