# Generated by Django 4.2 on 2023-10-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo_file_school_settings'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('school', 'username')},
        ),
    ]
