# Generated by Django 4.2 on 2023-05-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.AddField(
            model_name='school',
            name='logo_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_of_establishment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='tag',
            field=models.SlugField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='website_url',
            field=models.URLField(null=True),
        ),
    ]
