# Generated by Django 4.2 on 2023-06-30 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassUser',
            new_name='ClassMember',
        ),
        migrations.AlterModelTable(
            name='classmember',
            table='class_members',
        ),
    ]
