# Generated by Django 4.2 on 2023-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="tag",
            field=models.SlugField(max_length=10, null=True, unique=True),
        ),
    ]
