# Generated by Django 4.2 on 2023-08-09 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmember',
            name='school',
            field=models.ForeignKey(default='12d8e90b-f7b0-4ab8-b826-2d3940e38c70', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
