# Generated by Django 4.2 on 2023-09-19 22:43

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AddField(
            model_name='school',
            name='settings',
            field=models.JSONField(default=school.models.School.default_settings),
        ),
    ]
