# Generated by Django 4.2 on 2023-05-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_logo_school_logo_file_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='school',
            table='schools',
        ),
    ]
