# Generated by Django 4.2 on 2023-05-19 02:53

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    School = apps.get_model("school", "School")
    for row in School.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_options_school_deleted_school_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
