# Generated by Django 4.2 on 2023-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='tag',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
