# Generated by Django 4.2 on 2023-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='tag',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
