# Generated by Django 4.2 on 2023-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_school_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
