# Generated by Django 4.2 on 2023-08-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_classmember_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmember',
            name='school',
            field=models.ForeignKey(default='4b7223f1-ad74-4c25-9edc-7913e16d90ee', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
    ]
