# Generated by Django 4.2 on 2023-05-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_created_at_alter_school_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='tag',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
