# Generated by Django 4.2 on 2023-05-23 00:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import partial_date.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=50)),
                ("active", models.BooleanField(null=True)),
                ("start_date", partial_date.fields.PartialDateField()),
                ("end_date", partial_date.fields.PartialDateField()),
                ("resumption_date", models.DateField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.school"
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
                "unique_together": {("school", "name", "active")},
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=50)),
                ("active", models.BooleanField(null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.school"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session.session",
                    ),
                ),
            ],
            options={
                "db_table": "terms",
                "unique_together": {("session", "name", "active")},
            },
        ),
    ]
