# Generated by Django 4.2 on 2023-08-19 21:51

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=partial_date.fields.PartialDateField(verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=partial_date.fields.PartialDateField(verbose_name='%Y'),
        ),
    ]
