# Generated by Django 4.2 on 2023-06-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.term'),
        ),
        migrations.AlterField(
            model_name='subjectselection',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.term'),
        ),
    ]
