# Generated by Django 4.2 on 2023-08-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('subject', '0003_alter_subject_school_alter_subjectselection_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='staff_assignments',
            field=models.ManyToManyField(related_name='assigned_subjects', through='subject.SubjectStaffAssignment', to='staff.staff'),
        ),
    ]
