# Generated by Django 4.2 on 2023-08-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_classmember_school'),
        ('subject', '0005_alter_subject_school_alter_subjectselection_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectselection',
            name='school',
            field=models.ForeignKey(default='4b7223f1-ad74-4c25-9edc-7913e16d90ee', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectstaffassignment',
            name='school',
            field=models.ForeignKey(default='4b7223f1-ad74-4c25-9edc-7913e16d90ee', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
    ]
