# Generated by Django 4.2 on 2023-10-17 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo_file_school_settings'),
        ('parent', '0002_alter_family_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='familyrole',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
