# Generated by Django 4.2 on 2023-06-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinformation",
            name="username",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
