# Generated by Django 4.2 on 2023-05-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrequest',
            name='comment_if_declined',
            field=models.TextField(blank=True, null=True),
        ),
    ]
