# Generated by Django 4.2 on 2023-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_studentinformation_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrequest',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
