# Generated by Django 4.2 on 2023-06-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentattendance',
            table='student attendance',
        ),
    ]
