# Generated by Django 4.2 on 2023-07-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_delete_studentattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
