# Generated by Django 4.2 on 2023-07-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_delete_studentattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
