# Generated by Django 4.2 on 2023-08-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_alter_attendancerecord_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
            preserve_default=False,
        ),
    ]
