# Generated by Django 4.2 on 2023-08-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancerecord_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10),
        ),
    ]
