# Generated by Django 4.2 on 2023-08-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10, null=True),
        ),
    ]
