# Generated by Django 4.2 on 2023-08-19 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0004_alter_classmember_school'),
        ('attendance', '0006_alter_attendancerecord_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendee',
            field=models.ForeignKey(default='a119f8df-e165-4201-a8d6-a714afdd46cb', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='school',
            field=models.ForeignKey(default='6023efc5-3ee7-40a2-81a2-eb42f166ff16', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
    ]
