# Generated by Django 4.2 on 2023-08-31 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0005_alter_classmember_school'),
        ('attendance', '0007_alter_attendancerecord_attendee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendee',
            field=models.ForeignKey(default='4b7223f1-ad74-4c25-9edc-7913e16d90ee', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='school',
            field=models.ForeignKey(default='4b7223f1-ad74-4c25-9edc-7913e16d90ee', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
    ]
