# Generated by Django 4.2 on 2023-07-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feeitem_discount_alter_feetemplate_discount'),
        ('fees', '0002_discount_description_discount_name_and_more'),
    ]

    operations = [
    ]
