# Generated by Django 4.2 on 2023-07-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feeitem_amount_alter_feeitem_tax_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
