# Generated by Django 4.2 on 2023-08-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_transaction_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_category',
            field=models.CharField(default='school_fees', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(default='flutterwave', max_length=100),
        ),
    ]
