# Generated by Django 4.2 on 2023-07-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='role',
            new_name='roles',
        ),
    ]
