# Generated by Django 4.2 on 2023-08-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_classmember_school'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(default='07b71576-f1a2-4648-873a-74ef4784b74b', on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
