# Generated by Django 4.2 on 2023-10-17 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo_file_school_settings'),
        ('staff', '0002_alter_staff_staff_number_alter_staff_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
