# Generated by Django 4.2 on 2023-10-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_logo_file_school_settings'),
        ('staff', '0003_staffrole_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrole',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='staffrole',
            unique_together={('school', 'name')},
        ),
    ]
